pronomen_ersetzungen_m = {
    # Drittpersonen müssen zuerst ersetzt werden, sonst wird die Ersetzung von der
    # Erst- auf die Dritttperson erneut übersetzt
    "er": "dieser",
    "sie": "diese",
    "ihn": "diesen",
    "ihr": "dieser",
    "ihm": "diesem",
    # Männliche Pronomenersetzung
    "ich": "er",
    "mein": "sein",
    "meine": "seine",
    "meinen": "seinen",
    "meinem": "seinem",
    "meiner": "seiner",
    "meines": "seines",
    "mich": "ihn/sich",
    "mir": "ihm",
    "wir": "sie",
    "unsere": "ihre",
    "unserem": "ihrem",
    "uns": "sich/ihnen",
}

pronomen_ersetzungen_w = {
    # Drittpersonen müssen zuerst ersetzt werden, sonst wird die Ersetzung von der
    # Erst- auf die Dritttperson erneut übersetzt
    "er": "dieser",
    "sie": "diese",
    "ihn": "diesen",
    "ihr": "dieser",
    "ihm": "diesem",
    # Weibliche Pronomenersetzung
    "ich": "sie",
    "mein": "ihr",
    "meine": "ihre",
    "meinen": "ihren",
    "meinem": "ihrem",
    "meiner": "ihrer",
    "meines": "ihres",
    "mich": "sie/sich",
    "mir": "ihr",
    "wir": "sie",
    "unsere": "ihre",
    "unserem": "ihrem",
    "uns": "sich/ihnen"
}

ocr_ersetzungen = {
    "lch": "Ich",
    "ln": "In",
    "lnformation": "Information",
    "lnformationen": "Informationen",
    "lnfo": "Info",
    "lnfos": "Infos",
    "ldee": "Idee",
    "ldeen": "Ideen",
    "lnsider": "Insider",
    "lrrtum": "Irrtum",
    "ldentifikation": "Identifikation",
    "lnstruktionen": "Instruktionen",
    "lnteresse": "Interesse",
    "lrgendwann": "Irgendwann",
    "lnhalt": "Inhalt",
    "lnhaltlich": "Inhaltlich",
    "lnterpretation": "Interpretation",
    "lnitiative": "Initiative",
    "lhnen": "Ihnen",
    "enruähnt": "erwähnt",
    "enruähnen": "erwähnen",
    "enryähnen": "erwähnen",
    "enrvähnen": "erwähnen",
    "enruartet": "erwartet",
    "normalenrueise": "normalerweise",
    "lnhaber": "Inhaber"
}

verben_ersetzung_praesens = {
    "hat": "habe",
    "ist": "sei",
    "soll": "solle",
    "kann": "könne",
    "hatte": "habe",
    "weiss": "wisse",
    "darf": "dürfe",
    "heisst": "heisse",
    "trifft": "treffe",
    "glaubt": "glaube",
    "schenkt": "schenke",
    "braucht": "brauche",
    "kauft": "kaufe",
    "will": "wolle",
    "kennt": "kenne",
    "lebt": "lebe",
    "übergibt": "übergebe",
    "tauscht": "tausche",
    "spielt": "spiele",
    "fühlt": "fühle",
    "hilft": "helfe",
    "schaut": "schaue",
    "denkt": "denke",
    "bringt": "bringe",
    "bemerkt": "bemerke",
    "benötigt": "benötige",
    "verfügt": "verfüge",
    "verdient": "verdiene",
    "möchte": "wolle",
    "sagt": "sage",
    "wohnt": "wohne",
    "besitzt": "besitze",
    "fällt": "falle",
    "verlange": "verlangte",
    "lauft": "laufe",
    "durchsucht": "durchsuche",
    "arbeitet": "arbeite",
    "nimmt": "nehme",
    "vermutet": "vermute",
    "stamme": "stammte",
    "belastet": "belaste",
    "holt": "hole",
    "täuscht": "täusche",
    "verliert": "verliere",
    "zielt": "ziele",
    "erhält": "erhalte",
    "interessiert": "interessiere",
    "steigt": "steige",
    "schaue": "schaue",
    "übernimmt": "übernehme",
    "bin": "sei",
    "haben": "hätten",
    "sind": "seien",
    "machen": "machten",
    "benötigen": "benötigten",
    "hatten": "hätten",
    "stammen": "stammten",
    "muss": "müsse",
    "wird": "werde",
    "gilt": "gelte",
    "geht": "gehe",
    "gibt": "gebe",
    "steht": "stehe",
    "befindet": "befinde",
    "kommt": "komme",
    "müssen": "müssten",
    "können": "könnten",
    "dürfen": "dürften",
    "stellt": "stelle",
    "zeigt": "zeige",
    "erstreckt": "erstrecke",
    "aussieht": "aussehe",
    "ergibt": "ergebe",
    "macht": "mache",
    "liegt": "liege",
    "hängt": "hänge",
    "bleibt": "bleibe",
    "stimmt": "stimme",
    "lautet": "laute",
    "bezieht": "beziehe",
    "stattfindet": "stattfinde",
    "findet": "finde",
    "entspricht": "entspreche",
    "entsprechen": "entsprächen",
    "handelt": "handle",
    "fehlt": "fehle",
    "fehlen": "fehlten",
    "tut": "tue",
    "besteht": "bestehe",
    "gehören": "gehörten",
    "setzt": "setze",
    "angeht": "angehe",
    "sieht": "sehe",
    "funktioniert": "funktioniere",
    "anbelangt": "anbelange",
    "dient": "diene",
    "erwartet": "erwarte",
    "enthält": "enthalte",
    "betrifft": "betreffe",
    "stimmen": "stimmten",
    "läuft": "laufe",
    "stammt": "stamme",
    "kostet": "koste",
    "passt": "passe",
    "entsteht": "entstehe",
    "erfolgt": "erfolge",
    "könnte": "könne",
    "folgt": "folge",
    "datiert": "datiere"
}

satzende_praesens = {
    "war": "gewesen sei",
    "waren": "gewesen seien",
    "kam": "gekommen sei",
    "kamen": "gekommen seien",
    "blieb": "geblieben sei",
    "blieben": "geblieben seien",
    "gab": "gegeben habe",
    "ging": "gegangen sei",
    "wurde": "worden sei",
    "befand": "befunden habe",
    "machte": "gemacht habe",
    "wusste": "gewusst habe",
    "sagte": "gesagt habe",
    "sagten": "gesagt hätten",
    "brauchte": "gebraucht habe",
    "brauchten": "gebraucht hätten"
}

verben_ersetzung_praeteritum = {
    "war": ["sei", "gewesen"],
    "waren": ["seien", "gewesen"],
    "hatte": ["habe", "gehabt"],
    "hatten": ["hätten", "gehabt"],
    "musste": ["habe", "müssen"],
    "mussten": ["hätten", "müssen"],
    "fuhr": ["sei", "gefahren"],
    "trug": ["habe", "getragen"],
    "befand": ["habe", "befunden"],
    "befanden": ["hätten", "befunden"],
    "lief": ["sei", "gelaufen"],
    "ging": ["sei", "gegangen"],
    "blieb": ["sei", "geblieben"],
    "kannte": ["habe", "gekannt"],
    "kannten": ["hätten", "gekannt"],
    "wusste": ["habe", "gewusst"],
    "wussten": ["hätten", "gewusst"],
    "stand": ["habe", "gestanden"],
    "standen": ["hätten", "gestanden"],
    "dachte": ["habe", "gedacht"],
    "dachten": ["hätten", "gedacht"],
    "nahm": ["habe", "genommen"],
    "nahmen": ["hätten", "genommen"],
    "sah": ["habe", "gesehen"],
    "sahen": ["hätten", "gesehen"],
    "kam": ["sei", "gekommen"],
    "kamen": ["seien", "gekommen"],
    "sagte": ["habe", "gesagt"],
    "sagten": ["hätten", "gesagt"],
    "wurde": ["sei", "worden"],
    "wurden": ["seien", "worden"],
    "brauchte": ["habe", "gebraucht"],
    "brauchten": ["hätten", "gebraucht"],
    "benötigte": ["habe", "benötigt"],
    "benötigten": ["hätten", "benötigt"],
    "konnte": ["habe", "gekonnt"],
    "konnten": ["hätten", "gekonnt"],
    "gab": ["habe", "gegeben"],
    "durfte": ["habe", "gedurft"],
    "durften": ["hätten", "dürfen"],
    "machte": ["habe", "gemacht"],
    "machten": ["hätten", "gemacht"],
    "spielte": ["habe", "gespielt"],
    "spielten": ["hätten", "gespielt"],
    "hielt": ["habe", "gehalten"],
    "hielten": ["hätten", "gehalten"],
    "wollte": ["habe", "wollen"],
    "wollten": ["hätten", "wollen"],
    "diente": ["habe", "gedient"],
    "dienten": ["hätten", "gedient"],
    "versuchte": ["habe", "versucht"],
    "versuchten": ["hätten", "versucht"],
    "brachte": ["habe", "gebracht"],
    "brachten": ["hätten", "gebracht"],
    "fand": ["habe", "gefunden"],
    "fanden": ["hätten", "gefunden"],
    "geriet": ["sei", "geraten"],
    "gerieten": ["seien", "geraten"],
    "fuhren": ["seien", "gefahren"],
    "verbrachte": ["habe", "verbracht"],
    "verbrachten": ["hätten", "verbracht"],
    "trank": ["habe", "getrunken"],
    "tranken": ["hätten", "getrunken"],
    "unterhielt": ["habe", "unterhalten"],
    "unterhielten": ["hätten", "unterhalten"],
    "besass": ["habe", "besessen"],
    "besassen": ["hätten", "besessen"],
    "fiel": ["sei", "gefallen"],
    "fielen": ["seien", "gefallen"],
    "verlangte": ["habe", "verlangt"],
    "verlangten": ["hätten", "verlangt"],
    "passierte": ["sei", "passiert"],
    "erklärte": ["habe", "erklärt"],
    "erklärten": ["hätten", "erklärt"],
    "traf": ["habe", "getroffen"],
    "trafen": ["hätten", "getroffen"],
    "bekam": ["habe", "bekommen"],
    "bekamen": ["hätten", "bekommen"],
    "löschte": ["habe", "gelöscht"],
    "löschten": ["hätten", "gelöscht"],
    "kostete": ["habe", "gekostet"],
    "vermutete": ["habe", "vermutet"],
    "vermuteten": ["hätten", "vermutet"],
    "passte": ["habe", "gepasst"],
    "passten": ["hätten", "gepasst"],
    "holte": ["habe", "geholt"],
    "holten": ["hätten", "geholt"],
    "zeigte": ["habe", "gezeigt"],
    "zeigten": ["hätten", "gezeigt"],
    "telefonierte": ["habe", "telefoniert"],
    "telefonierten": ["hätten", "telefoniert"],
    "bat": ["habe", "gebeten"],
    "baten": ["hätten", "gebeten"],
    "hörte": ["habe", "gehört"],
    "hörten": ["hätten", "gehört"],
    "sass": ["habe", "gesessen"],
    "sassen": ["hätten", "gesessen"],
    "schilderte": ["habe", "geschildert"],
    "schilderten": ["hätten", "geschildert"],
    "schrieb": ["habe", "geschrieben"],
    "schrieben": ["hätten", "geschrieben"],
    "logierte": ["habe", "logiert"],
    "logierten": ["hätten", "logiert"],
    "funktionierte": ["habe", "funktioniert"],
    "funktionierten": ["hätten", "funktioniert"],
    "lag": ["sei", "gelegen"],
    "lagen": ["seien", "gelegen"],
    "täuschte": ["habe", "getäuscht"],
    "täuschten": ["hätten", "getäuscht"],
    "zielte": ["habe", "gezielt"],
    "zielten": ["hätten", "gezielt"],
    "antwortete": ["habe", "geantwortet"],
    "antworteten": ["hätten", "geantwortet"],
    "rief": ["habe", "gerufen"],
    "riefen": ["hätten", "gerufen"],
    "stieg": ["sei", "gestiegen"],
    "stiegen": ["seien", "gestiegen"],
    "schaute": ["habe", "geschaut"],
    "schauten": ["hätten", "geschaut"],
    "übernahm": ["habe", "übernommen"],
    "übernahmen": ["hätten", "übernommen"],
    "öffnete": ["habe", "geöffnet"],
    "öffneten": ["hätten", "geöffnet"],
    "reagierte": ["habe", "reagiert"],
    "reagierten": ["hätten", "reagiert"],
    "begab": ["habe", "begeben"],
    "begaben": ["hätten", "begeben"],
    "führte": ["habe", "geführt"],
    "führten": ["hätten", "geführt"],
    "sprach": ["habe", "gesprochen"],
    "sprachen": ["hätten", "gesprochen"],
    "stiess": ["habe", "gestossen"],
    "stiessen": ["hätten", "gestossen"],
    "gelangte": ["sei", "gelangt"],
    "gelangten": ["seien", "gelangt"],
    "schloss": ["habe", "geschlossen"],
    "schlossen": ["hätten", "geschlossen"],
    "folgte": ["sei", "gefolgt"],
    "folgten": ["seien", "gefolgt"],
    "meinte": ["habe", "gemeint"],
    "meinten": ["hätten", "gemeint"],
    "zahlte": ["habe", "gezahlt"],
    "zahlten": ["hätten", "gezahlt"],
    "erfolgte": ["sei", "erfolgt"],
    "erfolgten": ["seien", "erfolgt"],
    "lautete": ["habe", "gelautet"],
    "lauteten": ["hätten", "gelautet"],
    "beantragte": ["habe", "beantragt"],
    "beantragten": ["hätten", "beantragt"]
}